### ISSUE TITLE
Is wasm-gc deprecated?

### ISSUE THREAD

**Issue by s1na** [axic/runevm#7]
I just noticed the build script is using `wasm-gc`, which according to this [repo](https://github.com/alexcrichton/wasm-gc) is no longer needed:

> The Rust compiler now natively supports --gc-sections when linking wasm executables, which means wasm executables already have 90% of their garbage removed when coming out of the compiler.

Can this be removed?

**Comment by axic** [comment]
It is true to a certain extent, but not fully. I have a change which replaces the entire build system in this repo with [chisel](https://github.com/wasmx/wasm-chisel) but didn't merge it since there was no way to test it as the repo doesn't compile :)
